services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'